name: Compilar EXE Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl pyinstaller

      - name: Compilar EXE
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed --name "Control_Inventario" inventario_base.py

      - name: Subir EXE compilado
        uses: actions/upload-artifact@v4
        with:
          name: Control_Inventario_Windows
          path: dist/Control_Inventario.exe
